name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: pygame-wasm-builder prepare
      run: |
            WD=$(pwd)
            python3 -V
            echo $WD
            clang --version | head -n 1
            echo
            gcc --version | head -n 1
            echo
            env|grep GITHUB
            echo
            grep "^Pkg.Revision =" ${ANDROID_HOME}/ndk-bundle/source.properties
            sudo apt-get update
            sudo apt-get install bash wget
            cd /home/runner/work/python-wasm-plus/python-wasm-plus
            echo adding emscripten support
            git clone https://github.com/emscripten-core/emsdk.git
            cd emsdk && ./emsdk install tot && ./emsdk activate tot
            cd /home/runner/work/python-wasm-plus/python-wasm-plus
            echo " === Building  ===="
            time bash ./python-wasm-plus.sh
            time bash ./buildapp.sh

